<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_robot">

  <!-- ======= Parameters ======= -->
  <xacro:property name="robot_length" value="0.25"/>
  <xacro:property name="robot_width"  value="0.25"/>
  <xacro:property name="robot_height" value="0.10"/>

  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width"  value="0.03"/>

  <xacro:property name="caster_radius" value="0.02"/>

  <!-- ======= Base Link ======= -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${robot_length} ${robot_width} ${robot_height}"/>
      </geometry>
      <origin xyz="0 0 ${robot_height/2}" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0.0 0.3 0.8 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${robot_length} ${robot_width} ${robot_height}"/>
      </geometry>
      <origin xyz="0 0 ${robot_height/2}" rpy="0 0 0"/>
    </collision>

    <inertial>
      <mass value="4"/>
      <origin xyz="0 0 ${robot_height/2}"/>
      <inertia
          ixx="0.02" ixy="0.0"  ixz="0.0"
          iyy="0.04" iyz="0.0"
          izz="0.05"/>
    </inertial>
  </link>

  <!-- ============================
       LEFT WHEEL
  ============================= -->
  <link name="left_wheel_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${wheel_width/2} 0" rpy="1.5707 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${wheel_width/2} 0" rpy="1.5707 0 0"/>
    </collision>

    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${robot_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>


  <!-- ============================
       RIGHT WHEEL
  ============================= -->
  <link name="right_wheel_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 -${wheel_width/2} 0" rpy="1.5707 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 -${wheel_width/2} 0" rpy="1.5707 0 0"/>
    </collision>

    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 -${robot_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>


  <!-- ============================
       FRONT CASTER
  ============================= -->
  <link name="front_caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin xyz="0 0 0" />
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>

    <collision>
      <geometry><sphere radius="${caster_radius}"/></geometry>
      <origin xyz="0 0 0"/>
    </collision>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster_link"/>
    <origin xyz="${robot_length/2 - 0.03} 0 -0.015"/>
  </joint>


  <!-- ============================
       REAR CASTER
  ============================= -->
  <link name="rear_caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin xyz="-0 0 0" />
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>

    <collision>
      <geometry><sphere radius="${caster_radius}"/></geometry>
      <origin xyz="-0 0 0"/>
    </collision>
  </link>

  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_caster_link"/>
    <origin xyz="-${robot_length/2 - 0.03} 0 -0.015"/>
  </joint>


  <!-- ============================
       LiDAR
  ============================= -->
  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder length="0.03" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${robot_height + 0.02}" rpy="0 0 0"/>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ============================
       CAMERA (đã đổi tên)
  ============================= -->
  <link name="camera_front_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.03"/>
      </geometry>
      <origin xyz="0 0 0" />
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="camera_front_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_front_link"/>
    <origin xyz="${robot_length/2} 0 ${robot_height}"/>
  </joint>

</robot>
